### ISSUE TITLE
How do you running the project? 

### ISSUE THREAD

**Issue by andy-da** [GoingMyWay/my_spell_correct#1]
Hi,I need you help,because i don't how to running the project,how to test result. Thanks.
1.$./make
g++ -g -o ./bin/main  ./src/*.*  -I./include/ -lpthread
./src/epoll_t.c: In function ‘void epoll_init(epoll_t*, int, callback_t)’:
./src/epoll_t.c:12:2: error: ‘d0’ was not declared in this scope
  d0{\
  ^
./src/epoll_t.c:25:3: note: in expansion of macro ‘ERR_EXIT’
   ERR_EXIT("epoll create error");
   ^
./src/epoll_t.c:27:18: error: ‘listenfd’ was not declared in this scope
  et->listenfd_ = listenfd;
                  ^
./src/epoll_t.c:29:6: error: ‘struct epoll_t’ has no member named ‘calllback_’
  et->calllback_ = callback;
      ^
./src/epoll_t.c: In function ‘void epoll_loop(epoll_t*)’:
./src/epoll_t.c:12:2: error: ‘d0’ was not declared in this scope
  d0{\
  ^
./src/epoll_t.c:44:3: note: in expansion of macro ‘ERR_EXIT’
   ERR_EXIT("epoll wait error");
   ^
./src/epoll_t.c:45:2: error: ‘else’ without a previous ‘if’
  else if(nready == 0)
  ^
./src/epoll_t.c: In function ‘void epoll_handle_fd(epoll_t*)’:
./src/epoll_t.c:12:2: error: ‘d0’ was not declared in this scope
  d0{\
  ^
./src/epoll_t.c:63:6: note: in expansion of macro ‘ERR_EXIT’
      ERR_EXIT("accept conn error");
      ^
./src/epoll_t.c:73:61: error: invalid conversion from ‘ssize_t (*)(int, void*, size_t, int) {aka long int (*)(int, void*, long unsigned int, int)}’ to ‘void*’ [-fpermissive]
     size_t nread = recv_msg_with_len(fd, recv,sizeof recvbuf);
                                                             ^
In file included from ./include/epoll_t.h:11:0,
                 from ./src/epoll_t.c:8:
./include/sysutil.h:51:8: note:   initializing argument 2 of ‘size_t recv_msg_with_len(int, void*, size_t)’
 size_t recv_msg_with_len(int sockfd, void *usrbuf, size_t bufsize);
        ^
./src/epoll_t.c:83:33: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
     printf("msg len:%d\n", nread);
                                 ^
./src/epoll_t.c: In function ‘void epoll_add_fd(epoll_t*, int)’:
./src/epoll_t.c:104:45: error: request for member ‘fd’ in ‘1’, which is of non-class type ‘int’
  if(epoll_ctl(et->epoll_fd_, EPOLL_CTL_ADD. fd, &ev) == -1)
                                             ^
./src/epoll_t.c:12:2: error: ‘d0’ was not declared in this scope
  d0{\
  ^
./src/epoll_t.c:105:3: note: in expansion of macro ‘ERR_EXIT’
   ERR_EXIT("epoll add fd");
   ^
./src/epoll_t.c: In function ‘void epoll_del_fd(epoll_t*, int)’:
./src/epoll_t.c:12:2: error: ‘d0’ was not declared in this scope
  d0{\
  ^
./src/epoll_t.c:114:3: note: in expansion of macro ‘ERR_EXIT’
   ERR_EXIT("epoll add fd");
   ^
./src/main.cpp: In function ‘void foo(const char*, size_t, int)’:
./src/main.cpp:28:32: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
  printf("receive msg:%d\n", cnt);
                                ^
makefile:2: recipe for target 'main' failed
make: *** [main] Error 1
2.$./start.sh
./start.sh: 7: ./start.sh: ./bin/main: not found

**Comment by GoingMyWay** [comment]
in `./src/epoll_t.c:12:2: error: ‘d0’ was not declared in this scope`, `d0` is `do`.

**Comment by andy-da** [comment]
$make
g++ -g -o ./bin/main  ./src/*.*  -I./include/ -lpthread
./src/epoll_t.c: In function ‘void epoll_init(epoll_t*, int, callback_t)’:
./src/epoll_t.c:25:18: error: ‘listenfd’ was not declared in this scope
  et->listenfd_ = listenfd;
                  ^
./src/epoll_t.c:27:6: error: ‘struct epoll_t’ has no member named ‘calllback_’
  et->calllback_ = callback;
      ^
./src/epoll_t.c: In function ‘void epoll_handle_fd(epoll_t*)’:
./src/epoll_t.c:71:61: error: invalid conversion from ‘ssize_t (*)(int, void*, size_t, int) {aka long int (*)(int, void*, long unsigned int, int)}’ to ‘void*’ [-fpermissive]
     size_t nread = recv_msg_with_len(fd, recv,sizeof recvbuf);
                                                             ^
                                 ^
./src/epoll_t.c: In function ‘void epoll_add_fd(epoll_t*, int)’:
./src/epoll_t.c:102:45: error: request for member ‘fd’ in ‘1’, which is of non-class type ‘int’
  if(epoll_ctl(et->epoll_fd_, EPOLL_CTL_ADD. fd, &ev) == -1)
                                             ^

makefile:2: recipe for target 'main' failed
make: *** [main] Error 1
